---
title: "StudyDesignFinal"
author: "Jonas Mikhaeil"
date: "2023-11-30"
output: html_document
---


```{r}
### high ICC
input$comp_prob <- .8
input$mu <- c(0.8,0.76,0.94,0.6,0.7,0.71)
input$sd <- 0.01
### low compliance
input$comp_prob <- 0.5
input$alpha <- c(0.1,-0.35,0.5,-0.1,-0.35,-0.15)
input$comp_prob <- 0.5
input$mu <- c(-0.2,0.2,0.2,-0.7,-0.1,0.5)
input$sd <- 0.59
### regular
input$comp_prob <- 0.8
input$alpha <- c(0.1,-0.35,0.5,-0.1,-0.35,-0.15)
input$comp_prob <- 0.5
input$mu <- c(-0.2,0.2,0.2,-0.7,-0.1,0.5)
input$sd <- 0.59
```

```{r}
input <- list()
input$alpha <- c(0.1,-0.35,0.5,-0.1,-0.35,-0.15)
input$comp_prob <- 0.8
input$mu <- c(-0.2,0.2,0.2,-0.7,-0.1,0.5)
input$sd <- 0.59
input$treat <- TRUE


probabiltiy_shd_given_riskScore <- function(risk_score,hospital){
    ### assume score is calibrated
    hosp<-c("columbia","allen","lawrence","cornell","low man","queens")
    
    alpha_hosp <- input$alpha
    alpha <- alpha_hosp[which(hospital==hosp)]
    invlogit(alpha+logit(risk_score))
  }
  
  p_echo_givenRS_ShD_treatment <- function(risk_score , shd , treatment_indicator){
    X <- input$comp_prob
    if (treatment_indicator ==0){
      if(shd == 1){
        p<-0.4+(0.8-0.4)/0.3*(risk_score-0.6)
      } 
      else{
        p<-0.4+(0.8-0.4)/0.3*(risk_score-0.6)
      } 
    }
    else{
      if(shd == 1){
        RZ <- rbinom(1,1,X)
        #p<-1^RZ*(0.4+(0.8-0.4)/0.3*(risk_score-0.6))^(1-RZ)
        p<-X + (1-X)*(0.4+(0.8-0.4)/0.3*(risk_score-0.6))
      }
      else{
        RZ <- rbinom(1,1,X)
        p<-X + (1-X)*(0.4+(0.8-0.4)/0.3*(risk_score-0.6))
        #p<-1^RZ*(0.4+(0.8-0.4)/0.3*(risk_score-0.6))^(1-RZ)
        
      }
    }
    p
  }
  simulate_data <- function(N){
    K <-6
    proportions_assigned_to_hospital <- c(0.2327044,0.1228834,0.1482825,0.2005322,0.1064344,0.1891630)
    hosp<-c("columbia","allen","lawrence","cornell","low man","queens")
    hosp_mu <- input$mu #c(0.005,0.06,0.12,0.02,0.03,0.11)
    hosp_var <- rep(input$sd^2,6)#c(0.005,0.06,0.12,0.02,0.03,0.11)
    
    N_K <- round(proportions_assigned_to_hospital*N)
    
    
    risk_score_vector <- numeric(0)
    
    # Generate risk scores for each hospital
    for (k in 1:length(N_K)) {
      mock <- c(0.7,0.7,0.5,0.5,0.7,0.7)
      risk_score_vector <- c(risk_score_vector,truncnorm::rtruncnorm(N_K[k],a=0.6,b=1.,hosp_mu[k],hosp_var[k])) 
    }
        risk_score <- data.frame(
      hospital = rep(hosp, times = N_K),
      risk_score = risk_score_vector
    )
    
    data <- risk_score %>% 
      rowwise() %>% 
      mutate(p_shd = probabiltiy_shd_given_riskScore(risk_score,hospital)) %>%
      mutate(shd = rbinom(1, 1, p_shd)) %>%
      ungroup() 
    ### ristricted randomization to ensure Columbia and Cornell are in different
    ### treatment groups
    if(input$treat==TRUE){
      treatment_indicator <- sample(1:K,round(K/2),replace = FALSE)
      while (which(hosp == "columbia") %in% treatment_indicator == which(hosp == "cornell") %in% treatment_indicator) {
        treatment_indicator <- sample(1:K, round(K/2), replace = FALSE)
      }}
    else treatment_indicator <-c()
    
    data$treatment <- ifelse(data$hospital %in% hosp[treatment_indicator], 1, 0)
    
    data <- data %>% 
      rowwise() %>% 
      mutate(p_echo = p_echo_givenRS_ShD_treatment(risk_score,shd,treatment))  %>% 
      mutate(echo=rbinom(1, 1, p_echo)) %>% 
      ungroup() 
    data$diagnosis <- ifelse(data$shd==1 & data$echo==1, 1, 0)
    
    data
  }
```

```{r}
data<-simulate_data(100000)

    hosp<-c("columbia","allen","lawrence","cornell","low man","queens")
    real_data <- data.frame(hospital=hosp,shd_rate=c(299/(111+299),207/(207+84),301/(301+51),282/(135+282),166/(72+166),372/(372+111)))
    rate_of_detected_shd <- data |>filter(echo == 1) |> aggregate(diagnosis~hospital,mean)
    plot1 <- ggplot(real_data,aes(x=hospital,y=shd_rate))+
      geom_point() + 
      geom_point(data=rate_of_detected_shd,aes(x=hospital,y=diagnosis),col="steelblue")+
      theme_minimal() +
      labs(title = "", x = "Hospital", y = "P(SHD | ECHO received)")+
      theme(axis.title.x=element_blank(),
            axis.text.x=element_blank(),
            axis.ticks.x=element_blank(),
             axis.title.y = element_text(size = 9))
    
    
    
    hosp<-c("columbia","allen","lawrence","cornell","low man","queens")
    real_data <- data.frame(hospital=hosp,shd_rate=c(299/(111+299),207/(207+84),301/(301+51),282/(135+282),166/(72+166),372/(372+111))
                            ,prob_echo =c(1-0.466,1-.427,1-.426,1-.497,1-.459,1-.382) )
    rate_of_echo <- data  |> aggregate(echo~hospital,mean)
    #colnames(rate_of_detected_shd)[3] <- "rate of shd in patients who \n received an echo"
    plot2 <- ggplot(real_data,aes(x=hospital,y=prob_echo))+
      geom_point() + 
      geom_point(data=rate_of_echo,aes(x=hospital,y=echo),col="steelblue")+
      theme_minimal() +
    labs(title = "", x = "Hospital", y = "P(ECHO)")+
    annotate(geom="text", x="queens", y=0.515, label="Simulated",color="steelblue")+
    annotate(geom="text", x="queens", y=0.50, label="Data",color="black")+
      theme(text = element_text(size=13),
             axis.title.y = element_text(size = 9))
    pdf("matching_cluster_coef.pdf",5,4)
    plot2 / plot1 & xlab(NULL) & theme(plot.margin = margin(5.5, 5.5, 0, 5.5))
    
```
```{r}
pdf("overallRS_hist.pdf",5,4)
N <- c(rep(0.65,1550),rep(0.75,1226),rep(0.85,900),rep(0.95,433)) 
   
    hist_dat <-data.frame(
      value=c(N,data$risk_score),
      cat= rep(c("h1", "h2"), times = c(length(N),length(data$risk_score))))
    ggplot(hist_dat, aes(x = value, fill = cat,y=..density..)) +
    geom_histogram(position = "identity", alpha = 0.5, breaks = c(0.6,0.7,0.8,0.9,1)) +
    scale_fill_manual( values=c("black", "steelblue")) +
    theme_minimal() +
    labs(title = "", x = "Risk Score", y = "")+
    theme(axis.text.y=element_blank(),
    axis.ticks.y=element_blank(),legend.position = "none")
```

```{r}
pdf("probs_g_rs.pdf",9,5)
    #data$treatment <- factor(data$treatment, levels=c("0", "1"), labels=c("control", "treatment"))
    plot1<- ggplot(data,aes(x=risk_score,y=p_echo,color=treatment))+
      scale_color_manual(values=c("black", "steelblue")) +
      geom_line()+
      theme_minimal()+
      theme(legend.position = "none",#c(0.8,0.3),
            legend.title=element_blank())+
      ylab("P(ECHO | Risk Score)")+
      annotate(geom="text",x=0.7,0.85,label="treatment",col="steelblue")+
        annotate(geom="text",x=0.9,0.68,label="control",col="black")

    plot2 <- 
      ggplot(data,aes(x=risk_score,y=p_shd,group=hospital))+
      geom_line()+
      theme_minimal() +
      ylab("P(SHD | Risk Score)")
    plot <- plot1 + plot2 & xlab(NULL) 
    wrap_elements(panel = plot) +
      labs(tag = "\nRisk Score") +
      theme(
        plot.tag = element_text(size = rel(1)),
        plot.tag.position = "bottom"
      )
```

### analysis

```{r}
prim_anal <- function(data){
VaryAClus <- data %>%
      group_by(treatment,hospital) %>%
      summarize(
        MeanyAClus = mean(diagnosis)
      ) %>%
      ungroup(.) %>%
      group_by(treatment) %>%
      summarize(
        VaryAClus = var(MeanyAClus)
      ) 
    # Total variance
    VaryA <- data %>%
      group_by(treatment) %>%
      summarize(
        VaryATot = var(diagnosis)
      )
      averages_by_treatment <- data %>%
        group_by(treatment) %>%
        summarise(
          diagnosis = mean(diagnosis),
          echo = mean(echo),
          "diagnosis per echo" =mean(diagnosis)/mean(echo),
          PPV = mean(shd)
        )   %>%
        left_join(VaryAClus,by='treatment') %>%
        left_join(VaryA,by='treatment') %>%
        mutate(
          ICC =  VaryAClus/VaryATot)
        
      # Print the results
      averages_by_treatment|> select("treatment","ICC","diagnosis","echo","diagnosis per echo","PPV")
      }
```






```{r,warning=FALSE,message=FALSE}
input$alpha <- c(0.1,-0.35,0.5,-0.1,-0.35,-0.15)
input$comp_prob <- 0.5
input$mu <- c(-0.2,0.2,0.2,-0.7,-0.1,0.5)
input$sd <- 0.59
 calculate_power <- function(N,multilevel=TRUE){
      alpha <- 0.05
      sig_level <- alpha/2
      
      rep <- seq(1:100)
      averages_by_treatment_list<- list()

      power <-sapply(rep,function(r){
        data <- simulate_data(N)
      
        #mod <- lm(diagnosis~treatment+risk_score,data=data)
        
        #var_te <- car::hccm(mod,type="hc2")["treatment","treatment"]
        #coef <- tidy(mod)
        ###using EHW standard errors (see (Lei and Ding, 2021))
        #if(clustering==TRUE){
          #VCovClusterHC1 <- sandwich::vcovCL(mod,cluster=data$hospital,type="HC1",sandwich=TRUE)
          #print(VCovClusterHC1)
          #var_te <-VCovClusterHC1["treatment","treatment"]
          #if(abs(coef$estimate[2]) - qnorm(1-sig_level) * sqrt(var_te)  > 0){r = 1}
          #else{r=0}
        #}
        if(multilevel==TRUE){
          mod <- lme4::lmer(diagnosis~treatment+ (1| hospital),data=data)
          
          te <- fixef(mod)["treatment"]
          te.se <- se.fixef(mod)["treatment"]
          if(abs(te) - qnorm(1-sig_level) * te.se  > 0){r = 1}
          else{r=0}
        }
        else{
           mod <- lm(diagnosis~treatment,data=data)
          coef <- tidy(mod)
          VCovClusterHC1 <- sandwich::vcovCL(mod,cluster=data$hospital,type="HC1",sandwich=TRUE)
          var_te <-VCovClusterHC1["treatment","treatment"]
          if(abs(coef$estimate[2]) - qnorm(1-sig_level) * sqrt(var_te)  > 0){r = 1}
          else{r=0}
        }
      }
      )
      
      power <- unlist(power) |> na.omit() |> mean()
    }
    N <- c(25,50,100,150,200,500,1000,2000)#c(50,75,100,200,250,500)
    K<-6
   
    
    
    power_by_n <- sapply(N,function(n)calculate_power(n,TRUE))

    power_Cluster <- data.frame(N=N,power_Cluster=power_by_n)
```

```{r}
#pdf("power_calc_HC.pdf",5,3)
 make_plot<-function(data){
      ggplot(data=data)+
        geom_line(mapping=aes(x=N,y=power_Cluster))+
        #geom_line(mapping=aes(x=N,y=power_HC),linetype = "dashed")+
        geom_hline(yintercept = 0.8)+
        scale_y_continuous(expand = c(0,0),,limits=c(0.,1),breaks = c(0,0.25,0.5,0.8))+
        scale_x_continuous(expand = c(0,0),limits=c(0,2100),breaks = c(0,100,250,500,1000,2000))+
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
              panel.background = element_blank(), axis.line = element_line(colour = "black"))+
        ylab(latex2exp::TeX("Power")) +
        xlab("Number of units (N)")
    }
    #plot(power$power_Cluster)
    make_plot(power_Cluster)
```




```{r,warning=FALSE,message=FALSE}

rep <- seq(1:1000)

  averages_by_treatment_list<- list()
  alpha <- 0.05
      sig_level <- alpha/2
  # Export necessary functions and libraries to the parallel environment
  clustering <-TRUE
   dummy<-sapply(rep,function(r){
    data <- simulate_data(1000)
    averages_by_treatment <- prim_anal(data) 
    averages_by_treatment$rep <- r
    averages_by_treatment_list[[r]] <<- averages_by_treatment
    #mod <- lm(diagnosis~treatment+risk_score,data=data)
    
    #var_te <- car::hccm(mod,type="hc2")["treatment","treatment"]
    #coef <- tidy(mod)
    ###using EHW standard errors (see (Lei and Ding, 2021))
    #if(clustering==TRUE){
      #VCovClusterHC1 <- sandwich::vcovCL(mod,cluster=data$hospital,type="HC1",sandwich=TRUE)
      #print(VCovClusterHC1)
      #var_te <-VCovClusterHC1["treatment","treatment"]
      #if(abs(coef$estimate[2]) - qnorm(1-sig_level) * sqrt(var_te)  > 0){r = 1}
      #else{r=0}
    #}
    
  }
  )
  
  combined_averages_by_treatment <- bind_rows(averages_by_treatment_list)
```
```{r}
combined_averages_by_treatment %>% group_by(treatment) %>% summarise(mean.ICC = mean(ICC),sd.ICC = sd(ICC),mean.diagnosis=mean(diagnosis)*100,sd.diagnosis=sd(diagnosis)*100,mean.echo=mean(echo)*100,sd.echo=sd(echo)*100,mean.PPV = mean(PPV),sd.PPV= sd(PPV),mean.diagpecho = mean(`diagnosis per echo`), sd.diagpecho = sd(`diagnosis per echo`))
```


```{r}
pdf("power_calc_reason.pdf",7,4)
 make_plot<-function(data){
      ggplot(data=data)+
        geom_line(mapping=aes(x=N,y=power_Cluster))+
        #geom_line(mapping=aes(x=N,y=power_HC),linetype = "dashed")+
        geom_hline(yintercept = 0.8)+
        scale_y_continuous(expand = c(0,0),,limits=c(0.,1),breaks = c(0,0.25,0.5,0.8))+
        scale_x_continuous(expand = c(0,0),limits=c(0,510),breaks = c(0,100,250,500))+
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
              panel.background = element_blank(), axis.line = element_line(colour = "black"))+
        ylab(latex2exp::TeX("Power")) +
        xlab("Number of units (N)")
    }
    #plot(power$power_Cluster)
    make_plot(power_Cluster)
```

